### ISSUE TITLE
Update license - libnest2d is now LGPL

### ISSUE THREAD

**Issue by noamgat** [markfink/nest2D#4]
https://github.com/tamasmeszaros/libnest2d/blob/master/LICENSE.txt

3 Months ago, the main dependency was changed to LGPL. Perhaps it is possible to update this one as well?

**Comment by noamgat** [comment]
Created pull request here:
https://github.com/markfink/nest2D/pull/5

**Comment by markfink** [comment]
looks good! thank you for the PR!
